### ISSUE TITLE
Needs more context

### ISSUE THREAD

**Issue by fed135** [Kikobeats/js-mythbusters#48]
Without context or explanation of the fundamentals, these "mythbusting" statements are of low value. See #25 

You need to take in account 
- V8 optimizers' impact based on different scenarios
- Hardware profile
- Browser/Node JS version

A very blatant example is in https://mythbusters.js.org/#/v8-tips/freeing-memory
Consider a scenario were your object is not used as a class-type element with an explicit structure, but rather like a dictionary were keys are added and removed dynamically. Setting keys to null will release the reference to the element, but the dictionary will still hold a pointer for that key, slowing down lookups significantly. 

With a clear example, you could illustrate the impact of both approaches.

An example for hardware profile would be the over usage of V8 C++ - side methods, which perform exponentially better on bigger hardware. You can witness this in libraries that implement protocols in pure-js versus their C++ bindings version. 

A lot of bundled JS methods also take advantage of this, like JSON.stringify/ JSON.parse. 
You can try benchmarking https://github.com/compactr/compactr.js on different machines to see just how big of a difference it makes.

For Node version, Buffers got a speed boost recently in Node 8. Prior to that, it was much faster to use arrays/ UINT8Arrays. In the browser, Buffers are polyfilled as UINT8Arrays anyways.

**Comment by Kikobeats** [comment]
Thanks for your comment!

I think you are right, because I started this project from my javascript background and I assumed things that should not be assumed from the vision of the user reading the site.

I feel the project between a fine line of performance but also not write too low level or clever code. This is why the documentation content tips about readibility.

About benchmark, I do not feel confident with them because

1) most of the benchmarks you can find are bad preconditions, so result is not deterministic.
2) as you mentioned, the result is could be different between node versions or browser.

Of course this is not an excuse for don't refutate documentation affirmations. 

My point was provide a bibliography section from people with more experience than me, but the most important thing I did the site more accesible to make possible anyone can edit a wrong or incomplete piece of documentation.

**Comment by fed135** [comment]
Don't get me wrong, this is a good initiative, I think it can help in the majority of cases. Most of the topics covered are on point and I don't know of anything like it right now. 

So I didn't mean to discourage you, quite the opposite. Performance in JS is a very complex topic and I think projects like yours are a step in the right direction.

I'm just trying to think of a way to verify or test assumptions in various contexts and environments. This could be under the shape of a runnable samples on the site using [benchmark](https://www.npmjs.com/package/benchmark) - which is somewhat consistant (not sure for reliability) and running those on vms with the desired os/node versions. 

Someday perhaps. I'll close the issue now. Thanks for hearing me out!
